### ISSUE TITLE
issues with ubuntu 20.04

### ISSUE THREAD

**Issue by yichungchen84** [Xilinx/RapidWright#107]
manual installation: 

1. gradle 6 compiling error due to 
Execution failed for task ':compileJava'.
> directory not found: $RapidWright_root/bin/generated/sources/annotationProcessor/java/main

so I use "make", it works

2. Libpng12 -> need to be installed from PPA for ubuntu 20.04 (and 18?)

**Comment by clavin-xlnx** [comment]
Thanks for pointing out these issues.  One solution that has been considered for Gradle is to use the gradle wrapper, this will lock down the version to be used with a known working set of commands that will compile.  I'll look into including that in a future release.

As for the Libpng12 need, this is due to RapidWright's dependence on an older Qt library for Java called Qt Jambi.  Eventually, we will move away from it, but for now it is a known issue (see [documentation]( http://www.rapidwright.io/docs/Automatic_Install.html)).

**Comment by yichungchen84** [comment]
Thank you.

**Comment by clavin-xlnx** [comment]
The gradle wrapper is now included with RapidWright as of 2020.2.5.  Closing this issue for now.
