### ISSUE TITLE
rapid_compile_ipi stuck on running 

### ISSUE THREAD

**Issue by maltanar** [Xilinx/RapidWright#3]
To try out rapid_ipi_compile I set up a small block design targeting  with four instances of the same IP, then sourced the rapidwright.tcl script and launched rapid_compile_ipi. Vivado seems to get stuck (I waited over an hour to see if it terminates, and it did not -- this is a small design where doing regular full synthesis finishes in <10min). The progress window says "Running config_ip_cache..." while the Vivado log says "Running opt_design jobs..."

I can see that the out-of-context synthesis for one instance is finished and the dcp file is generated (in both the ooc synthesis folder under runs as well as under $HOME/blockCache) but Vivado does not seem to be able to move past this.

Any tips on how I might be able to debug this? Thanks in advance.

**Comment by clavin-xlnx** [comment]
I had performed testing of rapid_ipi_compile previously and did not experience this issue.  However, I have tried again and seem to be experiencing the same behavior you describe.  I will look closer into what is going on.  

I have attempted to make RapidWright compatible for both Windows and Linux and wrote some classes (Job, JobQueue, LocalJob, LSFJob, ...) that are there to help manage multiple process runs concurrently.  There maybe an issue with the handling there that I missed.  The problem also could be in rapidwright.tcl itself.  On an unrelated note, I noticed several 'exec' commands that will likely fail in Windows and I will have to rewrite them such that they will work on both Linux/Windows.

**Comment by clavin-xlnx** [comment]
Ok, I have resolved the issue where the flow hangs during compile.  It came down to a typo of running Vivado in 'mode -tcl' instead of 'mode -batch'.  This, along with a few other things have been fixed as of [503b3c2](https://github.com/Xilinx/RapidWright/commit/503b3c223ceb52e7a8ec758f5b6f5689467efa1e).  Unfortunately, the automatic flow quality is quite low and is still under development, I would recommend for anything other than just testing things out to use an implementation guide file.

Thanks for proactively reporting!  Please reopen if you run into other issues.
