### ISSUE TITLE
EDIFNetlist.copyCellAndSubCells() does not copy library correctly

### ISSUE THREAD

**Issue by pongstorn-xilinx** [Xilinx/RapidWright#512]
EDIFNetlist.copyCellAndSubCells fails to copy some libraries associated with the given cell.

**Comment by eddieh-xlnx** [comment]
Please provide a standalone testcase, one which can serve as a test for the future fix.

**Comment by eddieh-xlnx** [comment]
It looks like `copyCellAndSubCells()` is copying cells into the work library:
https://github.com/Xilinx/RapidWright/blob/c2dad6174883913410ec9cdce6c7884f0d0e52ab/src/com/xilinx/rapidwright/edif/EDIFNetlist.java#L550-L556

Since `copyCellAndSubCells()` grew out from `migrateCellAndSubCells`:
https://github.com/Xilinx/RapidWright/blob/c2dad6174883913410ec9cdce6c7884f0d0e52ab/src/com/xilinx/rapidwright/edif/EDIFNetlist.java#L440-L446

@clavin-xlnx Is there any reason that I'm missing about why new cells and dumped into the work library rather than creating a new library with the same name, should it not exist?

**Comment by clavin-xlnx** [comment]
> @clavin-xlnx Is there any reason that I'm missing about why new cells and dumped into the work library rather than creating a new library with the same name, should it not exist?

Nope.  Dumping all the cells into work was the defacto solution in the past, but we've grown robust enough that we should be able to propagate all libraries going forward.
