### ISSUE TITLE
Missing Pin / WireIndex in BRAM (RSTRAMARSTRAML)

### ISSUE THREAD

**Issue by e7p** [Xilinx/RapidWright#635]
While utilizing a custom static net router, it occurs that some pins seems not to exist, in this case namely the "RSTRAMARSTRAML" wire of "RAMB36_X8Y14" in an Artix 7 200T. To reproduce (with current RapidWright version), run:

```
d = Design("top", "xc7a200t")
si = d.createSiteInst(d.device.getSite("RAMB36_X8Y14"))
d.getGndNet().createPin("RSTRAMARSTRAMU", si) # works
d.getGndNet().createPin("RSTRAMARSTRAML", si) # NullPointerException
```

If the pin exists in a loaded dcp from Vivado, the wireIndex is -1:
```
>>> design.getSiteInst("RAMB36_X8Y14").getSitePinInst("RSTRAMARSTRAMU").getRouteNode().getWire()
1120
>>> design.getSiteInst("RAMB36_X8Y14").getSitePinInst("RSTRAMARSTRAML").getRouteNode().getWire()
-1
>>> repr(design.getSiteInst("RAMB36_X8Y14").getSitePinInst("RSTRAMARSTRAML").getRouteNode())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
java.lang.ArrayIndexOutOfBoundsException: 65535
[...]
```

**Comment by eddieh-xlnx** [comment]
Great question @e7p, with a clear testcase to boot! It is a question that I couldn't immediately answer, but the process I undertook to find out more was this:

1. Open up the Vivado GUI, and create an empty design by running the Tcl: `link_design -part xc7a200t`.
2. Now select the site in question: `sel [get_sites RAMB36_X8Y14]`.
3. On the "Site Properties" window, note that the "General" tab shows that the primary (default) type of this site is `RAMBFIFO36E1`.
![image](https://user-images.githubusercontent.com/90657806/228082812-ddf4511b-51af-4fea-a607-2e3c24a18727.png)
4. Now navigate to the BELPins tab, and scroll to the `RST*` section:
![image](https://user-images.githubusercontent.com/90657806/228082993-52aaa4d5-c911-4239-8de5-9b9a4ba74868.png)
Notice that despite there being a `RSTRAMARSTRAMU`, there is no `RSTRAMARSTRAML` -- instead, there is a further `RST` suffix to get to `RSTRAMARSTRAMLRST`.

So the simple answer is that you're asking for a pin that does not exist. It's not clear to me why this inconsistency exists, but unfortunately it does and RapidWright represents it faithfully.

I do believe that the `NullPointerException` you're seeing is not a very good way of communicating that this site pin doesn't exist, and I would say an enhancement is in order to rectify this (you're more than welcome to give it a go!).

Now the bigger question is whether this is sufficient for your wider testcase, which if you could share I would be able to better point you in the right direction. For example, there are a number of types that this site can take (clicking on the Type dropdown box shows the other types) each with potentially different pin names (for example, it looks like `RSTRAMARSTRAML` does exist when the `RAMB36E1` type is selected). This type should be set by the placer (it certainly is by the Vivado placer), so if your placed design comes from Vivado then it should work. Furthermore, a Vivado placement will also set the cell pin mappings such that one can find the names of these physical pins from the `Cell` object, rather than a `SiteInst` object as you're doing now.

**Comment by eddieh-xlnx** [comment]
Firstly, I realised I wrote "BEL Pins" in my previous post when I meant "Site Pins", which I've now corrected.

> Unfortunately, I cannot find any method of a Cell object that could assist to find the correct wire, so I don't even see room for any dynamic workaround code to this issue.

The method I was thinking of is this one: https://github.com/Xilinx/RapidWright/blob/1db0b071dbbf7a3d666d1fbf54821f1d24ab4eb0/src/com/xilinx/rapidwright/design/DesignTools.java#L1840-L1849
which admittedly isn't in the `Cell` class.

You're right in that you wouldn't typically need to look at the `Cell` if the routing was set up correctly -- i.e. all `Net` objects contain all the `SitePinInst`-s they need -- but sometimes that's not the case (which is what I've been working on recently, so I had a little tunnel vision; sorry for leading you astray!) In any case, there are other methods that can populate such missing `SitePinInst`s too: https://github.com/Xilinx/RapidWright/blob/1db0b071dbbf7a3d666d1fbf54821f1d24ab4eb0/src/com/xilinx/rapidwright/design/DesignTools.java#L1774-L1781

> Also, it should be not desirable to have a method SitePinInst.getRouteNode() that may return a RouteNode without a proper wireIndex.

Agreed. I would say an exception would be a more reasonable outcome.

> Actually what I would need for a workaround is to get the mapping from RSTRAMARSTRAML to at least this covered BEL pin name RSTRAMARSTRAMLRST.

`DesignTools.getRoutedSitePin()` above allows you to go from a logical `Cell` pin to the name of the `Site` pin. This method internally calls:
https://github.com/Xilinx/RapidWright/blob/1db0b071dbbf7a3d666d1fbf54821f1d24ab4eb0/src/com/xilinx/rapidwright/design/DesignTools.java#L1854-L1863
which allows going from its `BEL` pin to the `Site` pin.

> Edit: Alternatively, it would help if Net has a function that returns the connected physical pin names instead of the SitePinInst. Or if Cell indeed is helpful, then a way from a net to its connected cells.

In case you're not aware, `Net.getPins()` provides a list of all `SitePinInst`-s on that net. The method `SitePinInst.getName()` provides the physical `Site` pin name.
Here's some example Python (note that this a DCP from Vivado, and I'm actually examining the VCC net since it's easier to route VCC and then to invert it in the slice, than it is to route GND):
```
bash-4.2$ cat bug635.py
import rapidwright
from com.xilinx.rapidwright.design import Design
d = Design.readCheckpoint('test/RapidWrightDCP/ramb18.dcp')
for p in d.getVccNet().getPins():
    print('Site:', p.getSite().getName(), 'Pin:', p.getName())
bash-4.2$ python3 bug635.py 
==============================================================================
==                         Reading DCP: ramb18.dcp                          ==
==============================================================================
 XML Parse & Device Load:     0.595s
            (EDIF Parse):            (    0.639s)
      (Read XDEF Header):            (    0.085s)
   (Read XDEF Placement):            (    0.633s)
     (Read XDEF Routing):            (    0.291s)
     Read Netlist & XDEF:     1.671s
------------------------------------------------------------------------------
         [No GC] *Total*:     2.266s
Site: TIEOFF_X6Y26 Pin: HARD1
Site: TIEOFF_X6Y27 Pin: HARD1
Site: TIEOFF_X6Y28 Pin: HARD1
Site: TIEOFF_X6Y25 Pin: HARD1
Site: TIEOFF_X6Y29 Pin: HARD1
Site: RAMB18_X0Y10 Pin: RSTRAMARSTRAM
Site: RAMB18_X0Y10 Pin: ADDRATIEHIGH0
Site: RAMB18_X0Y10 Pin: ADDRBTIEHIGH1
Site: RAMB18_X0Y10 Pin: REGCLKARDRCLK
Site: RAMB18_X0Y10 Pin: ADDRATIEHIGH1
Site: RAMB18_X0Y10 Pin: ADDRBTIEHIGH0
Site: RAMB18_X0Y10 Pin: WEA0
Site: RAMB18_X0Y10 Pin: WEA1
Site: RAMB18_X0Y10 Pin: RSTREGARSTREG
Site: RAMB18_X0Y10 Pin: WEA2
Site: RAMB18_X0Y10 Pin: WEA3
Site: RAMB18_X0Y10 Pin: ENBWREN
Site: RAMB18_X0Y10 Pin: ENARDEN
Site: RAMB18_X0Y10 Pin: RSTRAMB
Site: RAMB18_X0Y10 Pin: RSTREGB
Site: RAMB18_X0Y10 Pin: REGCLKB
```

**Comment by e7p** [comment]
> In any case, there are other methods that can populate such missing `SitePinInst`s too:
> 
> https://github.com/Xilinx/RapidWright/blob/1db0b071dbbf7a3d666d1fbf54821f1d24ab4eb0/src/com/xilinx/rapidwright/design/DesignTools.java#L1781

Unfortunately there doesn't seem to be a missing `SitePinInst`:
```
>>> DesignTools.createMissingSitePinInsts(design, design.getVccNet())
[]
```

> > Actually what I would need for a workaround is to get the mapping from RSTRAMARSTRAML to at least this covered BEL pin name RSTRAMARSTRAMLRST.
> 
> `DesignTools.getRoutedSitePin()` above allows you to go from a logical `Cell` pin to the name of the `Site` pin. This method internally calls:
> 
> https://github.com/Xilinx/RapidWright/blob/1db0b071dbbf7a3d666d1fbf54821f1d24ab4eb0/src/com/xilinx/rapidwright/design/DesignTools.java#L1863
> 
> 
> which allows going from its `BEL` pin to the `Site` pin.

These always seem to return None for me:
```
>>> DesignTools.getRoutedSitePin(cell, design.getVccNet(), "RSTRAMARSTRAML")
>>> DesignTools.getRoutedSitePin(cell, design.getVccNet(), "RSTRAMARSTRAMU")
>>> DesignTools.getRoutedSitePin(cell, design.getVccNet(), "RSTRAMARSTRAMLRST")
>>> DesignTools.getRoutedSitePin(cell, design.getVccNet(), "RSTRAMARSTRAM")
>>> DesignTools.getRoutedSitePin(cell, design.getVccNet(), "RAMB36_X8Y14.RSTRAMARSTRAML")
>>> DesignTools.getRoutedSitePinFromPhysicalPin(cell, design.getVccNet(), "RSTRAMARSTRAML")
>>> DesignTools.getRoutedSitePinFromPhysicalPin(cell, design.getVccNet(), "RSTRAMARSTRAMU")
>>>
```

> > Edit: Alternatively, it would help if Net has a function that returns the connected physical pin names instead of the SitePinInst. Or if Cell indeed is helpful, then a way from a net to its connected cells.
> 
> In case you're not aware, `Net.getPins()` provides a list of all `SitePinInst`-s on that net. The method `SitePinInst.getName()` provides the physical `Site` pin name. Here's some example Python (note that this a DCP from Vivado, and I'm actually examining the VCC net since it's easier to route VCC and then to invert it in the slice, than it is to route GND):

`Net.getPins()` is what I use. When running the same code on a DCP generated with Vivado 2020.1 I get the following results. I assume, it doesn't matter much if we want to route GND or VCC, as it was explained it can be inverted in the slice. Further, I use a RAMB36 instance and I think that this bug is specific to the RAMB36, so it shouldn't occur using RAMB18.

```
>>> d = Design.readCheckpoint('ramb36.dcp')
==============================================================================
==                         Reading DCP: ramb36.dcp                          ==
==============================================================================
 XML Parse & Device Load:     0.001s
              EDIF Parse:     0.094s
        Read XDEF Header:     0.004s
        Read XDEF Caches:     0.004s
     Read XDEF Placement:     0.009s
       Read XDEF Routing:     0.083s
------------------------------------------------------------------------------
         [No GC] *Total*:     0.196s
>>> for p in d.getVccNet().getPins():
...     print('Site:', p.getSite().getName(), 'Pin:', p.getName())
... 
('Site:', u'TIEOFF_X108Y73', 'Pin:', u'HARD1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTRAMARSTRAML')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTRAMARSTRAMU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL9')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL12')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL14')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'CLKARDCLKL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'CLKARDCLKU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU9')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU12')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU14')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRARDADDRL15')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL15')
('Site:', u'TIEOFF_X108Y72', 'Pin:', u'HARD1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL10')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU10')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL3')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL7')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU4')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU0')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ENARDENU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU5')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ENARDENL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL5')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ENBWRENU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU2')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU6')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ENBWRENL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL2')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL6')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU3')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEU7')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL0')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'WEBWEL4')
('Site:', u'TIEOFF_X108Y71', 'Pin:', u'HARD1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTRAMBL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTRAMBU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL11')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRL13')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'CLKBWRCLKL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'CLKBWRCLKU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU11')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'ADDRBWRADDRU13')
('Site:', u'TIEOFF_X108Y74', 'Pin:', u'HARD1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTREGARSTREGL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTREGARSTREGU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'REGCLKARDRCLKL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'REGCLKARDRCLKU')
('Site:', u'TIEOFF_X108Y70', 'Pin:', u'HARD1')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTREGBL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'RSTREGBU')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'REGCLKBL')
('Site:', u'RAMB36_X8Y14', 'Pin:', u'REGCLKBU')
```

Problematic still is the following:
```
>>> for p in d.getVccNet().getPins():
...     print('Site:', p.getSite().getName(), 'Pin:', p.getName(), 'RouteNode:', p.getRouteNode())
... 
('Site:', u'TIEOFF_X108Y73', 'Pin:', u'HARD1', 'RouteNode:', INT_R_X99Y73/VCC_WIRE 0 0 HVCCGNDOUT)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
java.lang.ArrayIndexOutOfBoundsException: 65535
	at com.xilinx.rapidwright.device.h.a(Unknown Source)
	at com.xilinx.rapidwright.device.Tile.getWireIntentCode(Unknown Source)
	at com.xilinx.rapidwright.router.RouteNode.getIntentCode(RouteNode.java:322)
	at com.xilinx.rapidwright.router.RouteNode.toString(RouteNode.java:294)
	at org.python.core.PyJavaType$8.__call__(PyJavaType.java:1071)
	at org.python.core.PyObjectDerived.__repr__(PyObjectDerived.java:104)
	at org.python.core.PyTuple.subobjRepr(PyTuple.java:301)
	at org.python.core.PyTuple.tuple___repr__(PyTuple.java:317)
	at org.python.core.PyTuple.toString(PyTuple.java:306)
	at org.python.core.PyObject.__repr__(PyObject.java:231)
	at org.python.core.PyObject.__str__(PyObject.java:266)
	at org.python.core.StdoutWrapper.printToFile(StdoutWrapper.java:108)
	at org.python.core.StdoutWrapper.print(StdoutWrapper.java:186)
	at org.python.core.StdoutWrapper.println(StdoutWrapper.java:272)
	at org.python.core.Py.println(Py.java:1905)
	at org.python.pycode._pyx140.f$0(<stdin>:1)
	at org.python.pycode._pyx140.call_function(<stdin>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.Py.exec(Py.java:1731)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277)
	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:130)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:115)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:62)
	at org.python.util.InteractiveConsole.push(InteractiveConsole.java:188)
	at org.python.util.InteractiveConsole._interact(InteractiveConsole.java:169)
	at org.python.util.InteractiveConsole.interact(InteractiveConsole.java:127)
	at org.python.util.jython.runStream(jython.java:394)
	at org.python.util.jython.main(jython.java:669)
	at com.xilinx.rapidwright.util.RapidWright.main(RapidWright.java:221)
java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 65535
```

**Comment by eddieh-xlnx** [comment]
Can you share your `ramb36.dcp` to make sure we're both looking at the same thing please?

**Comment by e7p** [comment]
Sure, find it here: [ramb36.zip](https://github.com/Xilinx/RapidWright/files/11109670/ramb36.zip)

**Comment by eddieh-xlnx** [comment]
Thanks @e7p. There are a number of issues here. 

Firstly, the benchmark you submitted instantiates a `RAMB36E1` site type:
```
$ cat bug635.py
import rapidwright
from com.xilinx.rapidwright.design import Design
d = Design.readCheckpoint('ramb36.dcp')
si = d.getSiteInstFromSiteName('RAMB36_X8Y14')
print(si.getSiteType())
bash-4.2$ python3 bug635.py
==============================================================================
==                         Reading DCP: ramb36.dcp                          ==
==============================================================================
<<SNIP>>
RAMB36E1
```

As I said earlier, the default site type is `RAMB36FIFOE1`, which does not have a `RSTRAMARSTRAML` site pin and hence `NullPointerException` as in your first post:
```
$ cat bug635.py
import rapidwright
from com.xilinx.rapidwright.design import Design
d = Design("top", "xc7a200t")
si = d.createSiteInst(d.getDevice().getSite("RAMB36_X8Y14"))
print(si.getSiteType())
$ python3 bug635.py
RAMBFIFO36E1
```

Modifying your original design to set the same site type fixes your NPE:
```
d = Design("top", "xc7a200t")
si = d.createSiteInst(d.getDevice().getSite("RAMB36_X8Y14"))
si.setSiteTypeEnum(SiteTypeEnum.RAMB36E1)
d.getGndNet().createPin("RSTRAMARSTRAMU", si)
d.getGndNet().createPin("RSTRAMARSTRAML", si)
```

However, there is a separate bug you've also rightly stumbled upon in `SitePinInst.getRouteNode()` which I'll file and fix, but will require a new release. A workaround -- if you really need a `RouteNode` object -- is to do:
```
import rapidwright
from com.xilinx.rapidwright.design import Design
from com.xilinx.rapidwright.device import SiteTypeEnum
from com.xilinx.rapidwright.router import RouteNode
d = Design("top", "xc7a200t")
si = d.createSiteInst(d.getDevice().getSite("RAMB36_X8Y14"))
si.setSiteTypeEnum(SiteTypeEnum.RAMB36E1)
d.getGndNet().createPin("RSTRAMARSTRAMU", si)
p = d.getGndNet().createPin("RSTRAMARSTRAML", si)
n = p.getConnectedNode()
rn = RouteNode(n.getTile(), n.getWire())
print('Site:', p.getSite().getName(), 'Pin:', p.getName(), 'RouteNode:', rn)
```
which correctly outputs:
```
Site: RAMB36_X8Y14 Pin: RSTRAMARSTRAML RouteNode: BRAM_R_X99Y70/BRAM_FIFO36_RSTRAMARSTRAMLRST 0 0 INPUT
```

**Comment by e7p** [comment]
> Thanks @e7p. There are a number of issues here.
> 
> Firstly, the benchmark you submitted instantiates a `RAMB36E1` site type:
> 
> ```
> $ cat bug635.py
> import rapidwright
> from com.xilinx.rapidwright.design import Design
> d = Design.readCheckpoint('ramb36.dcp')
> si = d.getSiteInstFromSiteName('RAMB36_X8Y14')
> print(si.getSiteType())
> bash-4.2$ python3 bug635.py
> ==============================================================================
> ==                         Reading DCP: ramb36.dcp                          ==
> ==============================================================================
> <<SNIP>>
> RAMB36E1
> ```

Right, I created it using Vivado, instantiating it as RAMB36E1. Thus I expect from Vivado to create the correct pins and to have all required route nodes available in RapidWright.


> As I said earlier, the default site type is `RAMB36FIFOE1`, which does not have a `RSTRAMARSTRAML` site pin and hence `NullPointerException` as in your first post:

Well, just to confirm, also with `RAMB36E1` the NPE occurs when adding the line `print([p.getRouteNode() for p in d.getVccNet().getPins())` to your bug635.py.

> Modifying your original design to set the same site type fixes your NPE:

According to the RapidWright documentation `SiteInst.setSiteTypeEnum()` is no valid function as is `.getSiteType()` instead of `.getSiteTypeEnum()`

> However, there is a separate bug you've also rightly stumbled upon in `SitePinInst.getRouteNode()` which I'll file and fix, but will require a new release. A workaround -- if you really need a `RouteNode` object -- is to do:

Glad to hear that the bugs will be taken care of. The workaround however won't easily work as I rely on designs created by Vivado and modifying the Routing with RapidWright in the second step. See above, the SiteType cannot be set retrospectively.

**Comment by eddieh-xlnx** [comment]
1. In the first half of your first post, you showed an example where you create a design inside RapidWright, and then tried to connect a particular site pin name to the gnd net. For the reasons explained, this site pin does not exist on the default site type, and thus a NPE was encountered. This NPE will become a more meaningful message as of https://github.com/Xilinx/RapidWright/pull/642.  
In order to create a `SiteInst` with a specific `SiteTypeEnum` consider [this overload](https://www.rapidwright.io/javadoc/com/xilinx/rapidwright/design/Design.html#createSiteInst-java.lang.String-com.xilinx.rapidwright.device.SiteTypeEnum-com.xilinx.rapidwright.device.Site-).

2. In the second half of that same first post, you demonstrated how even using a Vivado placed design (`ramb36.dcp`) triggers a `SitePinInst.getRouteNode()` bug. This will be addressed in https://github.com/Xilinx/RapidWright/pull/641 available with the next release, and I provided a workaround to get the `RouteNode` should you really need it.

> The workaround however won't easily work as I rely on designs created by Vivado.

The workaround I propose works even for Vivado designs:
```
import rapidwright
from com.xilinx.rapidwright.design import Design
from com.xilinx.rapidwright.device import SiteTypeEnum
from com.xilinx.rapidwright.router import RouteNode
d = Design.readCheckpoint("ramb36.dcp")
si = d.getSiteInstFromSiteName("RAMB36_X8Y14")
p = si.getSitePinInst("RSTRAMARSTRAML")
rn = RouteNode(p.getTile(), p.getConnectedWireIndex())
print('Site:', p.getSite().getName(), 'Pin:', p.getName(), 'RouteNode:', rn)
```
