### ISSUE TITLE
Interchange Device Resources

### ISSUE THREAD

**Issue by reillymck** [Xilinx/RapidWright#90]
At BYU, we were looking at the Device Resources example on the interchange branch and comparing with the XDLRC format. We were wondering if the configuration bits could be added to the Device Resources representation?

**Comment by clavin-xlnx** [comment]
Unfortunately, since Xilinx does not document most configuration bits, that won't be possible.  There are several configuration bits that are documented through the `write_bitstream -logic_location_file` option, and it is possible that at some point in the future there might be some utility in adding them to the device resources schema, but it would probably be a long term horizon item.
